### ISSUE TITLE
Shouldn't have to provide job name if no experiment name

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-v2-preview#112]
Title should be pretty self-descriptive.

I can already submit a job **in an experiment** without providing a name, and AML generates a GUID for the name. I can also submit a job **not in an experiment** with a name, and it goes under a "Default" experiment.

I should be able to do both:

> Submit a job providing neither experiment nor name &mdash; it should end up with an auto-generated name under the "Default" experiment.

AB#994193

**Comment by dkmiller** [comment]
cc: @jpe316 , @lostmygithubaccount

**Comment by jpe316** [comment]
Works for me - @brandonh-msft

**Comment by brandonh-msft** [comment]
> Works for me - @brandonh-msft

@jpe316 I'm assuming you picked the wrong Brandon? :)

**Comment by jpe316** [comment]
https://github.com/Azure/azureml-v2-preview/pull/120
