### ISSUE TITLE
Secret default exp 

### ISSUE THREAD

**Issue by swinner95** [Azure/azureml-v2-preview#113]
If  I don’t provide the experiment name, there is a secret default experiment where jobs go. Users may not know there is an experiment called default or they may not read the documentation .  Can we show a message in the CLI to inform the user when they submit a job with no experiment name that they have to look in the default exp in the UI please?

AB#994196

**Comment by paulshealy1** [comment]
The experiment name is displayed on job submission, and this will be documented in the v1 -> v2 transition docs.
