### ISSUE TITLE
Unhelpful error message when attempting to install the extension in incompatible CLI version

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-v2-preview#130]
Try installing the Azure ML extension in an old version of the Azure CLI:

```
az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.10-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y
```

If the Azure CLI version is too low (e.g., `2.7.0`) the resulting error message is pretty unhelpful:

![image](https://user-images.githubusercontent.com/5003801/103800673-8a468980-5001-11eb-8b0e-fc5d565004af.png)

**Recommendation*:: the error message should say which extension is attempting to be installed, and should point users to a link showing up to upgrade their installation of the Azure CLI.

AB#1001957

**Comment by paulshealy1** [comment]
@dkmiller the "None" part will be fixed when we go public preview. The message itself is from the Azure CLI. Can you open an issue on their repo at https://github.com/Azure/azure-cli?
