### ISSUE TITLE
Unhelpful error message when `azureml:` prefix is missing

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-v2-preview#131]
Try creating a job, with compute name "just" the compute cluster name (i.e., missing the `azureml:` prefix). The error message is not especially helpful:

![image](https://user-images.githubusercontent.com/5003801/103806308-ad753700-5009-11eb-94df-240aaf7b8055.png)

Good things: it tells you where in the YAML file there is a problem.

Bad things: if you don't already know what an "arm-id" is, this is completely unhelpful. [Googling that term is **not** helpful](https://www.google.com/search?q=arm-id). Even searching [azure arm id](https://www.google.com/search?q=azure+arm+id) doesn't give you anything useful. Worse, for people who do know about ARM IDs, this leads them to believe you can **only** specify compute via something like

> /subscriptions/48bbc269-ce89-4f6f-9a12-c6f91fcb772d/resourceGroups/aml1p-rg/providers/Microsoft.MachineLearningServices/workspaces/aml1p-ml-wus2/...

when in fact you can put `azureml:...`.

**Recommendation:** provide an example of a correct-looking ARM ID in the error message. Same for environments.

AB#1002113

**Comment by luigiw** [comment]
Great point, we should prob not say arm id even, because it's not.

**Comment by paulshealy1** [comment]
@dkmiller thanks for the feedback! We will address this soon.

**Comment by mx-iao** [comment]
Fixed with latest CLI version.
