### ISSUE TITLE
CLI should support `-w` for specifying workspace name

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-v2-preview#133]
The CLI already supports `-g` for resource group, it's a bit inconsistent to not have an abbreviation for specifying the workspace name.

**Recommendation:** support `az ml job create --file job.yml -w ws_name -g rg_name -s subscription_id`.

AB#1002154

**Comment by dkmiller** [comment]
Update from discussion:

----

This isn't forbidden by the Azure CLI. We should do this!

**Comment by mx-iao** [comment]
Done.
