### ISSUE TITLE
'ServicePrincipalSection' object has no attribute 'sas_token' 

### ISSUE THREAD

**Issue by waiyujack** [Azure/azureml-v2-preview#207]
## Describe the issue

I was having an issue when going through the first example [create your first job](https://azure.github.io/azureml-v2-preview/_build/html/quickstart/jobs.html#create-your-first-job) by running the "hello world" python script using

`az ml job create --file azureml-v2-preview/examples/train/basic-command-job/hello_python_job.yml`

I have changed the compute name in the yaml (so shouldn't be the compute ) and running the above code gave me an error saying 

_'ServicePrincipalSection' object has no attribute 'sas_token'_ 

I have checked my existing service principal using the code below and it gives me empty results i.e. []. 

`az ad sp list --show-mine --query "[].{id:appId, tenant:appOwnerTenantId}"`

I am wondering if I should create a service principal myself before running the private preview examples.

AB#1071079

**Comment by mx-iao** [comment]
@luigiw do you know why @waiyujack is seeing this datastore-related error?

**Comment by waiyujack** [comment]
@mx-iao and @luigiw 
Thanks both, it seems like I didn't have admin control on the workspace. It now solved when getting the admin control
