### ISSUE TITLE
az ml data upload not available in version installed following installation guidance

### ISSUE THREAD

**Issue by lindacmsheard** [Azure/azureml-v2-preview#225]
Hi - you have an example script published as part of the dask example that uses `az ml data upload`. This is also available in the reference [here](https://azure.github.io/azureml-v2-preview/_build/html/reference/azure-ml.html#ml%20data%20upload).

But, when following the installation instructions at [https://azure.github.io/azureml-v2-preview/_build/html/overview/installation.html](https://azure.github.io/azureml-v2-preview/_build/html/overview/installation.html), 
I end up with an installation that doesn't support ml data upload: 
```
azureuser@vm-d12v2:~/cloudfiles/code/Users/lisheard$ az ml data upload -n nyctaxi -v 1 --path ./data/
'upload' is misspelled or not recognized by the system.

TRY THIS:
https://aka.ms/cli_ref
Read more about the command in reference docs
azureuser@vm-d12v2:~/cloudfiles/code/Users/lisheard$ az ml data -h

Group
    az ml data : Ml data.
        Command group 'ml' is experimental and under development. Reference and support levels:
        https://aka.ms/CLI_refstatus
Commands:
    create
    delete
    list
    show   : Shows the state of a data version in a yaml format. Default is most recently created
             version.
    update

For more specific examples, use: az find "az ml data"
```

AB#1107493

**Comment by lostmygithubaccount** [comment]
can you confirm the version of the CLI you're using with `az extension list`?

**Comment by lindacmsheard** [comment]
I installed on a box-fresh Azure ML CI created today (in a workspace created today):
```
[
  {
    "experimental": true,
    "extensionType": "whl",
    "name": "ml",
    "path": "/home/azureuser/.azure/cliextensions/ml",
    "preview": false,
    "version": "0.0.49"
  }
]
```

az version returns this: 
```
{
  "azure-cli": "2.20.0",
  "azure-cli-core": "2.20.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ml": "0.0.49"
  }
}
```
The install command used was
```
az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.49-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y
```


(also note that running `az upgrade` on Azure ML CIs has previously broken the azureml sdk for me with version conflicts, so haven't touched that!)

**Comment by mx-iao** [comment]
Hi Linda,

Please see my comment in this issue: https://github.com/Azure/azureml-v2-preview/issues/230

`az data upload` got replaced with `az data create` in the newer version of the CLI. Apologies for the delay in the docs update.

Closing as dupe.
